const SUPABASE_URL = "https://ahxghebygiokybanruag.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoeGdoZWJ5Z2lva3liYW5ydWFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA5NTU5OTksImV4cCI6MjEwNjUzMTk5OX0.ehkedfiL7zUpZa9GPmyfcbycB9T_xtBZjf8Bx6nWu50";
const supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
